//*****************************************************************************
//*****************************************************************************
//  FILENAME:  EEPROM.h
//  Version: 1.7, Updated on 2012/9/21 at 11:59:0
//  Generated by PSoC Designer 5.3.2710
//
//  DESCRIPTION:
//    EEPROM Module header file.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2012. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef EEPROM_INCLUDE
#define EEPROM_INCLUDE

/* include the global header file */
#include <m8c.h>

/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  EEPROM_Start         // class 1
#pragma fastcall16  EEPROM_Stop          // class 2
#pragma fastcall16  EEPROM_bE2Write      // class 4
#pragma fastcall16  EEPROM_E2Read        // class 4 

//-------------------------------------------------
// Prototypes of the EEPROM API.
//-------------------------------------------------
extern void  EEPROM_Start(void);      
extern void  EEPROM_Stop(void);
extern CHAR  EEPROM_bE2Write(WORD wAddr, BYTE * pbData, WORD wByteCount, CHAR cTemperature);
extern void  EEPROM_E2Read(WORD wAddr, BYTE * pbDataDest, WORD wByteCount);

//-------------------------------------------------
// Defines for EEPROM API's.
//-------------------------------------------------
/* Return value for bE2Write */
#define  EEPROM_NOERROR           0
#define  EEPROM_FAILURE          -1
#define  EEPROM_STACKOVERFLOW    -2

#define  EEPROM_START_BLOCK       0x1fe                              // Starting block of EEPROM EEPROM device
#define  EEPROM_START_ADDR        (0x1fe * 64)                       // absolute address of EEPROM EEPROM device
#define  EEPROM_LENGTH            0x40                               // length of EEPROM EEPROM device

#endif
// end of file EEPROM.h
